# Generated by Django 5.2.4 on 2025-07-11 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_image_alter_product_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
